# Generated by Django 2.2.2 on 2019-06-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=100)),
                ('line_ids', models.CharField(max_length=100)),
            ],
        ),
    ]
