# Generated by Django 2.2.2 on 2019-06-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
